name: Scanbuild test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # Ubuntu latest scan-build has issues 2024-09. This is a documentated hack
    # to run Fedora instead
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    env:
      CC: clang

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo dnf install -y libcurl-devel clang-analyzer autoconf automake libtool gawk
    - name: Build libmarias3
      run: |
        autoreconf -fi
        ./configure --enable-debug=yes
    - name: Scanbuild
      run:
        scan-build --use-cc=clang --use-c++=clang++ --status-bugs make
